export const jobCategories: Record<string, string[]> = {
  "Pharma Industry": [
    "Plant Head",
    "HR Head",
    "QC Head",
    "Production Head",

    "Production Operator",
    "Production Executive",
    "Production Supervisor",
    "Production Manager",
    "Packing Operator",
    "Packing Supervisor",
    "Quality Control (QC)",
    "Quality Assurance (QA)",
    "QA Executive",
    "QC Executive",
    "Microbiologist",
    "Chemist",
    "Pharmacist",
    "B.Pharm / M.Pharm Jobs",
    "Bsc & Msc Jobs",
    "Machine Operator",
    "Granulation Operator",
    "Compression Operator",
    "Coating Operator",
    "Filling Operator",
    "Injectable Operator",
    "Warehouse Executive",
    "Store Keeper",
    "Inventory Executive",
    "Dispatch Executive",
    "Documentation Executive",
    "Validation Executive",
    "Maintenance Technician",
    "Electrical Technician",
    "Mechanical Technician",
    "HVAC Technician",
    "ETP/STP Operator",
    "Utility Operator",
    "Helper",
    "Housekeeping",
    "Security Guard",
  ],
  "Cosmetic Industry": [
    "Plant Head",
    "HR Head",
    "QC Head",
    "Production Head",
    "Production Operator",
    "Production Executive",
    "Production Supervisor",
    "Production Manager",
    "Mixing Operator",
    "Filling Operator",
    "Packing Operator",
    "Labeling Operator",
    "Machine Operator",
    "QC Executive",
    "QA Executive",
    "Chemist",
    "Formulation Executive",
    "R&D Executive",
    "Warehouse Executive",
    "Store Keeper",
    "Inventory Executive",
    "Maintenance Technician",
    "Electrical Technician",
    "Mechanical Technician",
    "Helper",
    "Housekeeping",
  ],
  "Plastic Injection Moulding Industry": [
    "Plant Head",
    "HR Head",
    "QC Head",
    "Production Head",
    "Injection Moulding Operator",
    "Machine Operator",
    "Moulding Supervisor",
    "Production Supervisor",
    "Production Executive",
    "Production Manager",
    "Mould Setter",
    "Mould Maintenance Technician",
    "Process Technician",
    "Quality Inspector",
    "QC Executive",
    "Packing Operator",
    "Assembly Operator",
    "Grinder Operator",
    "Material Handler",
    "Store Keeper",
    "Maintenance Technician",
    "Electrical Technician",
    "Mechanical Technician",
    "Machine Helper",
    "General Helper",
  ],
  " SMT / LED / Bulb / AC Manufacturing Industry": [
    "Plant Head",
    "HR Head",
    "QC Head",
    "Production Head",
    "SMT Operator",
    "SMT Technician",
    "SMT Engineer",
    "SMT Supervisor",
    "Production Operator",
    "Production Supervisor",
    "Line Leader",
    "Pick & Place Operator",
    "Reflow Operator",
    "AOI Operator",
    "SPI Operator",
    "QC Inspector",
    "Quality Engineer",
    "LED Assembly Operator",
    "Bulb Assembly Operator",
    "LED Testing Operator",
    "Soldering Operator",
    "PCB Assembly Operator",
    "Driver Assembly Operator",
    "Packing Operator",
    "Quality Inspector",
    "Production Supervisor",
    "Maintenance Technician",
    "Helper",
    "AC Assembly Operator",
    "Refrigeration Technician",
    "HVAC Technician",
    "Compressor Assembly",
    "Wiring Technician",
    "Soldering Technician",
    "Testing Technician",
    "Production Operator",
    "Store/Warehouse Staff",
  ],
  "Electrical Manufacturing Industry": [
    "Plant Head",
    "HR Head",
    "QC Head",
    "Production Head",
    "Electrical Technician",
    "Electrician",
    "Electrical Engineer",
    "Production Engineer",
    "Production Operator",
    "Assembly Operator",
    "Wiring Technician",
    "Panel Wiring Technician",
    "Control Panel Technician",
    "Testing Technician",
    "Quality Inspector",
    "QC Engineer",
    "Maintenance Technician",
    "Maintenance Engineer",
    "Supervisor",
    "Store Keeper",
    "Warehouse Executive",
    "Packing Operator",
    "Helper",
  ],

  "Sheet Metal Industry": [
    "Plant Head",
    "HR Head",
    "QC Head",
    "Production Head",
    "Sheet Metal Worker",
    "Sheet Metal Operator",
    "CNC Operator",
    "VMC Operator",
    "Press Brake Operator",
    "Laser Cutting Operator",
    "Shearing Machine Operator",
    "Punching Machine Operator",
    "Production Operator",
    "Fabricator",
    "Production Supervisor",
    "Quality Inspector",
    "QC Engineer",
    "Tool & Die Maker",
    "Die Maintenance Technician",
    "Machine Maintenance Technician",
    "Electrical Technician",
    "Store Keeper",
    "Material Handler",
    "Helper",
  ],

  "Welding / Fabrication Industry": [
    "Plant Head",
    "HR Head",
    "QC Head",
    "Production Head",
    "Welder",
    "MIG Welder",
    "TIG Welder",
    "ARC Welder",
    "Gas Welder",
    "CO₂ Welder",
    "Fabricator",
    "Fabrication Supervisor",
    "Welding Supervisor",
    "Welding Inspector",
    "Production Supervisor",
    "Fitter",
    "Mechanical Fitter",
    "Gas Cutter",
    "Grinder Operator",
    "CNC Plasma Operator",
    "Machine Operator",
    "Quality Inspector",
    "Maintenance Technician",
    "Helper",
  ],

  "Footwear Industry": [
    "Plant Head",
    "HR Head",
    "QC Head",
    "Production Head",
    "Shoe Upper Operator",
    "Cutting Operator",
    "Stitching Operator",
    "Sewing Machine Operator",
    "Sole Press Operator",
    "Sole Assembly Operator",
    "Lasting Operator",
    "Finishing Operator",
    "Buffing Operator",
    "Grinding Operator",
    "Adhesive Operator",
    "Packing Operator",
    "Quality Inspector",
    "QC Executive",
    "Production Operator",
    "Production Supervisor",
    "Line Leader",
    "Store Keeper",
    "Warehouse Executive",
    "Dispatch Executive",
    "Helper",
  ],
  "ITI / Technical": [
    "ITI Fitter",
    "Electrician",
    "Welder",
    "Turner",
    "Machinist",
    "CNC Operator",
    "VMC Operator",
    "Technician",
    "Maintenance Technician",
    "Mechanical Technician",
    "Electrical Technician",
    "Electronics Technician",
  ],

  "Construction / Civil": [
    "Civil Engineer",
    "Site Engineer",
    "Civil Supervisor",
    "Site Supervisor",
    "Construction Worker",
    "Construction Helper",
    "Mason / Raj Mistri",
    "Bar Bender",
    "Shuttering Carpenter",
    "Carpenter",
    "Tile Fitter",
    "Plumber",
    "Painter",
  ],

  "Driver / Delivery": [
    "Car Driver",
    "Taxi / Cab Driver",
    "Bus Driver",
    "Truck / Heavy Vehicle Driver",
    "Ambulance Driver",
    "Delivery Executive",
    "Courier Executive",
    "Forklift Operator",
    "JCB Operator",
    "Crane Operator",
  ],

  "Warehouse / Logistics": [
    "Plant Head",
    "HR Head",
    "QC Head",
    "Production Head",
    "Warehouse Executive",
    "Warehouse Supervisor",
    "Store Executive",
    "Store Keeper",
    "Inventory Executive",
    "Packing Staff",
    "Picker / Packer",
    "Dispatch Executive",
    "Logistics Executive",
    "Supply Chain Executive",
  ],

  Security: [
    "Field Manager",
    "Operation Manager",
    "Security Guard",
    "Security Supervisor",
    "Security Officer",
    "Security Manager",
    "CCTV Operator",
    "CCTV Supervisor",
    "Gatekeeper",
    "Security Executive",
    "Bouncer",
  ],

  "Housekeeping & Facility Management": [
    "Housekeeping Boy/Girl",
    "Housekeeping Supervisor",
    "Housekeeping Executive",
    "Facility Supervisor",
    "Facility Manager",
    "Office Boy",
    "Pantry Boy",
    "Cleaner",
    "Deep Cleaning Staff",
    "Machine Cleaning Operator",
    "Hospital Housekeeping",
    "Hotel Housekeeping",
    "Industrial Housekeeping",
    "Mall Housekeeping",
    "Residential Housekeeping",
    "Gardener",
    "Pest Control Staff",
    "Waste Management Staff",
    "Security Guard",
    "Security Supervisor",
    "Laundry Staff",
    "Cook",
    "Kitchen Helper",
  ],

  " General Manufacturing Industry": [
    "Production Operator",
    "Machine Operator",
    "Assembly Operator",
    "Line Leader",
    "Production Supervisor",
    "Production Executive",
    "Production Manager",
    "Quality Inspector",
    "QC Executive",
    "QA Executive",
    "Maintenance Technician",
    "Electrical Technician",
    "Mechanical Technician",
    "Fitter",
    "Electrician",
    "Welder",
    "Fabricator",
    "CNC Operator",
    "VMC Operator",
    "Packing Operator",
    "Store Keeper",
    "Warehouse Executive",
    "Inventory Executive",
    "Dispatch Executive",
    "Material Handler",
    "Helper",
    "Apprentice",
  ],

  "Logistics & Warehouse": [
    "Warehouse Executive",
    "Warehouse Supervisor",
    "Store Keeper",
    "Store Executive",
    "Picker",
    "Packer",
    "Loader",
    "Unloader",
    "Material Handler",
    "Inventory Executive",
    "Dispatch Executive",
    "Delivery Executive",
    "Delivery Boy",
    "Driver",
    "E-commerce Delivery",
    "Forklift Operator",
    "Reach Truck Operator",
    "Warehouse Manager",
  ],

  " Office / HR / Accounts": [
    "HR Executive",
    "HR Assistant",
    "HR Recruiter",
    "Payroll Executive",
    "PF/ESIC Executive",
    "Admin Executive",
    "Admin Assistant",
    "Data Entry Operator",
    "Computer Operator",
    "Back Office Executive",
    "MIS Executive",
    "Accountant",
    "Accounts Executive",
    "Billing Executive",
    "Finance Executive",
    "SAP Executive",
    "Excel Executive",
    "Receptionist",
    "Telecaller",
    "Customer Support Executive",
  ],

  "Accounts & Finance": [
    "Accountant",
    "Accounts Executive",
    "Accounts Assistant",
    "Finance Executive",
    "Billing Executive",
    "Cashier",
    "MIS Executive",
    "Audit Executive",
    "GST Executive",
    "Payroll Executive",
    "Financial Analyst",
    "Collection Executive",
    "CA",
    "CMA",
  ],

  "Gardener / Landscaping": [
    "Gardener",
    "Garden Supervisor",
    "Landscape Worker",
    "Landscaping Supervisor",
    "Horticulture Assistant",
    "Nursery Worker",
    "Plant Caretaker",
    "Lawn Maintenance Worker",
  ],

  "Hotel / Hospitality": [
    "Hotel Manager",
    "Front Office Executive",
    "Receptionist",
    "Housekeeping",
    "Housekeeping Supervisor",
    "Cook",
    "Chef",
    "Commis",
    "Kitchen Helper",
    "Steward",
    "Waiter",
    "Room Attendant",
    "Laundry Staff",
    "Security Guard",
    "Store Keeper,",
    "Guest Relations Executive",
    "Reservation Executive",
    "Bell Boy",
    "Concierge",
    "Restaurant Manager",
    "Waiter / Steward",
    "Banquet Supervisor",
  ],

  "Hospital / Healthcare": [
    "Doctor",
    "MBBS Doctor",
    "Pharmacist",
    "Nurse",
    "Staff Nurse",
    "Lab Technician",
    "Medical Lab Technician",
    "Radiology Technician",
    "OT Technician",
    "Pharmacy Assistant",
    "Receptionist",
    "Hospital Housekeeping",
    "Ward Boy",
    "Ward Assistant",
    "Data Entry Operator",
    "Billing Executive",
    "Medical Representative",
    "Staff Nurse",
    "GNM / ANM Nurse",
    "Nursing Assistant",
    "ICU / OT Nurse",
    "Nursing Supervisor",
    "Hospital Administrator",
    "Patient Care Executive",
    "Ward Boy",
    "Lab Technician",
    "Phlebotomist",
    "X-Ray Technician",
    "ECG Technician",
    "Pharmacist",
    "Caregiver",
    "Patient Attendant",
  ],

  "Restaurant / Food": [
    "Chef",
    "Sous Chef",
    "Commis Chef",
    "Cook",
    "Tandoor Chef",
    "Bakery Chef",
    "Kitchen Helper",
    "Dishwasher",
    "Food & Beverage Executive",
    "F&B Supervisor",
  ],

  "Teaching / Education": [
    "School Principal",
    "School Coordinator",
    "PGT Teacher",
    "TGT Teacher",
    "PRT / Primary Teacher",
    "Nursery Teacher",
    "English Teacher",
    "Mathematics Teacher",
    "Science Teacher",
    "Computer Teacher",
    "Home Tutor",
    "Librarian",
  ],

  "Banking / Insurance": [
    "Banking Executive",
    "Relationship Manager",
    "Loan Executive",
    "Credit Officer",
    "Insurance Advisor",
    "Insurance Sales Executive",
    "Bancassurance Executive",
    "Field Officer",
    "Collection Officer",
  ],

  "HR / Recruitment": [
    "HR Manager",
    "HR Executive",
    "HR Assistant",
    "HR Recruiter",
    "Recruitment Executive",
    "Talent Acquisition Executive",
    "Recruitment Coordinator",
    "Payroll Executive",
    "Training & Development Executive",
  ],

  "Office / Back Office": [
    "Office Administrator",
    "Office Coordinator",
    "Office Assistant",
    "Executive Assistant",
    "Personal Assistant",
    "Office Boy",
    "Back Office Executive",
    "Documentation Executive",
    "Computer Operator",
    "Clerk",
    "Typist",
  ],

  "Computer / IT": [
    "Data Entry Operator",
    "Computer Operator",
    "IT Support Executive",
    "Web Developer",
    "Software Developer",
    "App Developer",
    "Full Stack Developer",
    "Software Tester / QA",
    "Network Engineer",
    "System Administrator",
    "Cloud / DevOps Engineer",
    "Cyber Security Executive",
    "AI / ML Engineer",
  ],
  "SAP & Oracle": [
    "SAP Basis Administrator",
    "SAP ABAP Developer",
    "SAP FICO Consultant",
    "SAP SD Consultant",
    "SAP MM Consultant",
    "SAP HCM Consultant",
    "SAP SuccessFactors Consultant",
    "SAP S/4HANA Consultant",
    "Oracle DBA",
    "Oracle Developer",
    "Oracle Functional Consultant",
  ],
  "AutoCad & Solid Work": [
    "AutoCad Draughtsman",
    "Solid Work Designer",
    "Mechanical Designer",
    "Civil Draughtsman",
    "Architectural Draughtsman",
    "Electrical Draughtsman",
    "Draftsman",
    "CAD Technician",
  ],

  "BPO / Call Center": [
    "Telecaller",
    "Telesales Executive",
    "Call Center Executive",
    "Customer Care Executive",
    "Customer Support Executive",
    "Voice Process Executive",
    "Non-Voice Process Executive",
    "Chat Support Executive",
    "Customer Relationship Executive",
    "BPO Team Leader",
  ],

  "Sales / Marketing": [
    "Sales Executive",
    "Sales Manager",
    "Sales Officer",
    "Sales Coordinator",
    "Sales Consultant",
    "Marketing Executive",
    "Marketing Manager",
    "Field Sales Executive",
    "Business Development Executive",
    "Area Sales Manager",
    "Brand Promoter",
  ],

  "Digital Marketing / Creative": [
    "Digital Marketing Executive",
    "SEO Executive",
    "Social Media Executive",
    "Social Media Manager",
    "Content Writer",
    "Graphic Designer",
    "Video Editor",
    "Photographer",
    "Content Creator",
    "Performance Marketing Executive",
  ],

  "Retail / Store": [
    "Store Manager",
    "Store Incharge",
    "Store Executive",
    "Retail Sales Executive",
    "Cashier",
    "Counter Sales Executive",
    "Supermarket Staff",
    "Retail Associate",
    "Inventory Executive",
    "Visual Merchandiser",
  ],

  "House Maid / Domestic Help": [
    "House Maid",
    "Home Helper",
    "Domestic Worker",
    "Household Cook",
    "Home Cook",
    "House Cleaner",
    "Domestic Helper",
    "Live-in Maid",
    "Part-time Maid",
    "Full-time Maid",
  ],

  "Fire & Safety": [
    "Fire Safety Officer",
    "Fire Safety Supervisor",
    "Fireman",
    "Fire Technician",
    "Fire Alarm Technician",
    "Fire Fighting Technician",
    "Safety Officer",
    "Safety Supervisor",
    "Safety Executive",
    "EHS Executive",
    "EHS Officer",
    "Safety Engineer",
  ],

  "Automobile / Garage": [
    "Automobile Technician",
    "Automobile Mechanic",
    "Car Mechanic",
    "Bike Mechanic",
    "Service Advisor",
    "Service Technician",
    "Auto Electrician",
    "Denting Technician",
    "Painting Technician",
    "Workshop Supervisor",
    "Spare Parts Executive",
  ],

  "Power / Solar / Electrical": [
    "Electrical Engineer",
    "Electrical Technician",
    "Electrician",
    "Solar Technician",
    "Solar Engineer",
    "Solar Installer",
    "Solar Supervisor",
    "Solar Sales Executive",
    "Battery Technician",
    "Electrical Supervisor",
  ],

  "Airport / Aviation": [
    "Airport Ground Staff",
    "Airport Customer Service",
    "Airport Security",
    "Baggage Handler",
    "Cargo Executive",
    "Airport Receptionist",
    "Ticketing Executive",
    "Reservation Executive",
    "Ground Operations Executive",
  ],

  "Agriculture / Farming": [
    "Farm Worker",
    "Agriculture Supervisor",
    "Agriculture Executive",
    "Agriculture Field Officer",
    "Farm Manager",
    "Nursery Worker",
    "Horticulture Worker",
    "Tractor Operator",
    "Agricultural Technician",
    "Field Assistant",
  ],

  "Media / Photography": [
    "Photographer",
    "Videographer",
    "Video Editor",
    "Photo Editor",
    "Camera Operator",
    "Content Creator",
    "News Reporter",
    "Digital Content Writer",
    "Production Assistant",
  ],

  "Legal / Documentation": [
    "Legal Assistant",
    "Legal Executive",
    "Legal Advisor",
    "Documentation Executive",
    "Compliance Executive",
    "Compliance Officer",
    "Court Clerk",
    "Legal Intern",
    "Contract Executive",
  ],

  "Internship / Apprenticeship": [
    "HR Intern",
    "Accounts Intern",
    "IT Intern",
    "Marketing Intern",
    "Graphic Design Intern",
    "Software Development Intern",
    "Mechanical Apprentice",
    "Electrical Apprentice",
    "Production Apprentice",
    "Quality Apprentice",
    "Graduate Apprentice",
    "Technician Apprentice",
  ],

  "Purchase / Procurement": [
    "Purchase Executive",
    "Purchase Assistant",
    "Purchase Officer",
    "Purchase Manager",
    "Procurement Executive",
    "Procurement Officer",
    "Procurement Manager",
    "Procurement Specialist",
    "Procurement Coordinator",
    "Buyer",
    "Senior Buyer",
    "Strategic Buyer",
    "Purchase Coordinator",
    "Vendor Development Executive",
    "Vendor Development Manager",
    "Vendor Management Executive",
    "Supplier Relationship Executive",
    "Sourcing Executive",
    "Sourcing Manager",
    "Strategic Sourcing Specialist",
    "Purchase Analyst",
    "Procurement Analyst",
  ],

  "Production Planning / Industrial Engineering": [
    "Production Planner",
    "Production Planning Executive",
    "Production Planning Officer",
    "Production Planning Manager",
    "PPC Executive",
    "PPC Engineer",
    "PPC Officer",
    "PPC Manager",
    "Industrial Engineer",
    "Industrial Engineering Executive",
    "Process Engineer",
    "Process Improvement Engineer",
    "Process Improvement Executive",
    "Manufacturing Engineer",
    "Manufacturing Engineering Executive",
    "Operations Engineer",
    "Operations Executive",
    "Operations Manager",
    "Plant Engineer",
    "Plant Manager",
    "Work Study Officer",
    "Work Study Engineer",
    "Lean Manufacturing Engineer",
    "Continuous Improvement Engineer",
  ],

  "Maintenance / Engineering": [
    "Maintenance Engineer",
    "Maintenance Executive",
    "Maintenance Supervisor",
    "Maintenance Manager",
    "Mechanical Engineer",
    "Electrical Engineer",
    "Electronics Engineer",
    "Instrumentation Engineer",
    "Instrumentation Technician",
    "Mechatronics Engineer",
    "Mechatronics Technician",
    "Automation Engineer",
    "Automation Technician",
    "PLC Programmer",
    "PLC Technician",
    "Control Systems Engineer",
    "Utility Engineer",
    "Utility Technician",
    "Plant Maintenance Engineer",
    "Preventive Maintenance Engineer",
    "Maintenance Planner",
    "Maintenance Fitter",
    "Mechanical Supervisor",
    "Electrical Supervisor",
  ],

  "Engineering Design": [
    "Design Engineer",
    "Mechanical Design Engineer",
    "Electrical Design Engineer",
    "Civil Design Engineer",
    "Structural Design Engineer",
    "CAD Engineer",
    "CAD Designer",
    "AutoCAD Designer",
    "SolidWorks Designer",
    "3D CAD Designer",
    "Design Executive",
    "Design Manager",
    "Draftsman",
    "Mechanical Draftsman",
    "Civil Draftsman",
    "Electrical Draftsman",
    "Design Technician",
  ],

  "Food Processing": [
    "Food Processing Operator",
    "Food Processing Executive",
    "Food Production Supervisor",
    "Food Production Manager",
    "Food Processing Technician",
    "Food Processing Worker",
    "Food Packer",
    "Food Packing Operator",
    "Food Product Handler",
    "Food Quality Inspector",
    "Food Quality Analyst",
    "Food Safety Executive",
    "Food Safety Officer",
    "Food Technologist",
    "Food Technology Executive",
    "Bakery Production Supervisor",
    "Baking Assistant",
    "Dairy Processing Operator",
    "Fruit Processing Operator",
    "Vegetable Processing Operator",
    "Cold Storage Operator",
  ],

  "Real Estate / Property": [
    "Real Estate Agent",
    "Property Dealer",
    "Real Estate Executive",
    "Real Estate Sales Executive",
    "Real Estate Sales Manager",
    "Property Consultant",
    "Property Advisor",
    "Leasing Executive",
    "Leasing Manager",
    "Property Manager",
    "Real Estate Relationship Manager",
    "Site Acquisition Executive",
    "Real Estate Telecaller",
    "Real Estate Business Development Executive",
    "Property Coordinator",
  ],

  "Customer Service / Client Success": [
    "Customer Service Executive",
    "Customer Service Representative",
    "Customer Service Officer",
    "Customer Service Manager",
    "Customer Support Executive",
    "Customer Support Representative",
    "Client Service Executive",
    "Client Relationship Executive",
    "Client Relationship Manager",
    "Client Success Executive",
    "Customer Success Executive",
    "Customer Success Manager",
    "Customer Experience Executive",
    "Customer Experience Manager",
    "Helpdesk Executive",
    "Service Desk Executive",
    "Technical Support Executive",
    "Complaint Resolution Executive",
  ],

  "Telecom": [
    "Telecom Technician",
    "Telecom Engineer",
    "Telecom Field Engineer",
    "Network Technician",
    "Network Engineer",
    "Fiber Technician",
    "Fiber Optic Technician",
    "Fiber Splicing Technician",
    "Broadband Technician",
    "Installation Technician",
    "Telecom Field Executive",
    "Telecom Supervisor",
    "Telecom Project Engineer",
    "Tower Technician",
    "Tower Climber",
    "RF Engineer",
    "NOC Engineer",
    "NOC Executive",
  ],

  "Chemical / Petroleum": [
    "Chemical Engineer",
    "Chemical Technician",
    "Chemical Operator",
    "Process Operator",
    "Plant Operator",
    "Chemical Plant Operator",
    "Chemical Supervisor",
    "Chemical Plant Manager",
    "Process Engineer",
    "Petroleum Engineer",
    "Oil & Gas Technician",
    "Refinery Operator",
    "Refinery Technician",
    "Production Chemist",
    "Quality Control Chemist",
    "Laboratory Chemist",
    "Chemical Lab Technician",
  ],

  "Insurance": [
    "Insurance Advisor",
    "Insurance Agent",
    "Insurance Sales Executive",
    "Insurance Relationship Manager",
    "Insurance Manager",
    "Insurance Officer",
    "Insurance Operations Executive",
    "Insurance Claims Executive",
    "Claims Officer",
    "Claims Manager",
    "Claims Analyst",
    "Underwriting Executive",
    "Underwriter",
    "Underwriting Manager",
    "Insurance Processing Executive",
    "Policy Servicing Executive",
    "Insurance Telecaller",
    "Bancassurance Executive",
    "Insurance Renewal Executive",
  ],

  "Government / Public Sector": [
    "Government Clerk",
    "Junior Assistant",
    "Senior Assistant",
    "Data Entry Operator",
    "Office Assistant",
    "LDC",
    "UDC",
    "Stenographer",
    "Junior Secretariat Assistant",
    "Government Accountant",
    "Tax Assistant",
    "Income Tax Inspector",
    "GST Inspector",
    "Police Constable",
    "Sub Inspector",
    "Forest Guard",
    "Forest Officer",
    "Patwari",
    "Village Development Officer",
    "Panchayat Assistant",
    "Government Teacher",
    "Government Engineer",
    "Junior Engineer",
    "Assistant Engineer",
    "Government Nurse",
    "Government Pharmacist",
    "Lab Technician",
  ],

  "Printing / Packaging": [
    "Printing Operator",
    "Printing Machine Operator",
    "Offset Printing Operator",
    "Digital Printing Operator",
    "Printing Supervisor",
    "Printing Manager",
    "Packaging Operator",
    "Packaging Supervisor",
    "Packaging Executive",
    "Packaging Manager",
    "Packing Machine Operator",
    "Packaging Designer",
    "Prepress Operator",
    "DTP Operator",
    "Binding Operator",
    "Printing Quality Inspector",
    "Packaging Quality Inspector",
  ],

  "Fashion / Apparel": [
    "Fashion Designer",
    "Fashion Design Assistant",
    "Fashion Stylist",
    "Fashion Consultant",
    "Fashion Merchandiser",
    "Apparel Merchandiser",
    "Garment Merchandiser",
    "Fashion Illustrator",
    "Pattern Designer",
    "Pattern Master",
    "Tailor",
    "Master Tailor",
    "Boutique Manager",
    "Boutique Assistant",
    "Fashion Sales Executive",
  ],

  "Solar Panel": [
    "Solar Technician",
    "Solar Engineer",
    "Solar Installer",
    "Solar Supervisor",
    "Solar Sales Executive",
    "Solar Project Engineer",
    "Solar Project Manager",
    "Solar O&M Technician",
    "Solar Maintenance Technician",
    "Wind Turbine Technician",
    "Wind Energy Engineer",
    "Wind Farm Technician",
    "Renewable Energy Engineer",
    "Renewable Energy Technician",
    "Renewable Energy Project Manager",
    "Battery Technician",
    "Battery Engineer",
    "Energy Storage Technician",
    "EV Charging Technician",
  ],

  "EV / Electric Vehicle": [
    "EV Technician",
    "EV Mechanic",
    "EV Service Technician",
    "EV Maintenance Technician",
    "EV Battery Technician",
    "EV Battery Engineer",
    "EV Charging Technician",
    "EV Charging Station Operator",
    "EV Service Advisor",
    "EV Sales Executive",
    "EV Sales Consultant",
    "EV Diagnostic Technician",
    "Automotive Electrician",
    "Electric Vehicle Engineer",
    "EV Production Operator",
  ],
};

export const jobCategoryNames: string[] = Object.keys(jobCategories);
