export const jobCategories: Record<string, string[]> = {
  "Factory / Manufacturing": [
    "Production Executive",
    "Production Supervisor",
    "Production Manager",
    "Production Operator",
    "Assembly Operator",
    "Machine Operator",
    "Line Leader",
    "Line Supervisor",
    "Factory Worker",
    "Factory Helper",
  ],
  "ITI / Technical": [
    "ITI Fitter",
    "Electrician",
    "Welder",
    "Turner",
    "Machinist",
    "CNC Operator",
    "VMC Operator",
    "Technician",
    "Maintenance Technician",
    "Mechanical Technician",
    "Electrical Technician",
    "Electronics Technician",
  ],
  "Construction / Civil": [
    "Civil Engineer",
    "Site Engineer",
    "Civil Supervisor",
    "Site Supervisor",
    "Construction Worker",
    "Construction Helper",
    "Mason / Raj Mistri",
    "Bar Bender",
    "Shuttering Carpenter",
    "Carpenter",
    "Tile Fitter",
    "Plumber",
    "Painter",
  ],
  "Driver / Delivery": [
    "Car Driver",
    "Taxi / Cab Driver",
    "Bus Driver",
    "Truck / Heavy Vehicle Driver",
    "Ambulance Driver",
    "Delivery Executive",
    "Courier Executive",
    "Forklift Operator",
    "JCB Operator",
    "Crane Operator",
  ],
  "Warehouse / Logistics": [
    "Warehouse Executive",
    "Warehouse Supervisor",
    "Store Executive",
    "Store Keeper",
    "Inventory Executive",
    "Packing Staff",
    "Picker / Packer",
    "Dispatch Executive",
    "Logistics Executive",
    "Supply Chain Executive",
  ],
  "Security": [
    "Security Guard",
    "Security Supervisor",
    "Security Officer",
    "Security Manager",
    "CCTV Operator",
    "CCTV Supervisor",
    "Gatekeeper",
    "Security Executive",
    "Bouncer",
  ],
  "Housekeeping / Cleaning": [
    "Housekeeping Staff",
    "Housekeeping Supervisor",
    "Housekeeping Executive",
    "Room Attendant",
    "Cleaner",
    "Office Cleaner",
    "Hospital Cleaner",
    "Hotel Cleaner",
    "Laundry Attendant",
    "Deep Cleaning Staff",
  ],
  "Gardener / Landscaping": [
    "Gardener",
    "Garden Supervisor",
    "Landscape Worker",
    "Landscaping Supervisor",
    "Horticulture Assistant",
    "Nursery Worker",
    "Plant Caretaker",
    "Lawn Maintenance Worker",
  ],
  "Hotel / Hospitality": [
    "Hotel Manager",
    "Front Office Manager",
    "Receptionist",
    "Guest Relations Executive",
    "Reservation Executive",
    "Bell Boy",
    "Concierge",
    "Restaurant Manager",
    "Waiter / Steward",
    "Banquet Supervisor",
  ],
  "Restaurant / Food": [
    "Chef",
    "Sous Chef",
    "Commis Chef",
    "Cook",
    "Tandoor Chef",
    "Bakery Chef",
    "Kitchen Helper",
    "Dishwasher",
    "Food & Beverage Executive",
    "F&B Supervisor",
  ],
  "Hospital / Healthcare": [
    "Staff Nurse",
    "GNM / ANM Nurse",
    "Nursing Assistant",
    "ICU / OT Nurse",
    "Nursing Supervisor",
    "Hospital Administrator",
    "Patient Care Executive",
    "Ward Boy",
    "Lab Technician",
    "Phlebotomist",
    "X-Ray Technician",
    "ECG Technician",
    "Pharmacist",
    "Caregiver",
    "Patient Attendant",
  ],
  "Pharma / Medical": [
    "Medical Representative",
    "Medical Sales Executive",
    "Medical Store Manager",
    "Pharma Sales Executive",
    "Medical Coder",
    "Clinical Research Associate",
    "Drug Safety Associate",
  ],
  "Teaching / Education": [
    "School Principal",
    "School Coordinator",
    "PGT Teacher",
    "TGT Teacher",
    "PRT / Primary Teacher",
    "Nursery Teacher",
    "English Teacher",
    "Mathematics Teacher",
    "Science Teacher",
    "Computer Teacher",
    "Home Tutor",
    "Librarian",
  ],
  "Accounts & Finance": [
    "Accountant",
    "Accounts Executive",
    "Accounts Assistant",
    "Finance Executive",
    "Billing Executive",
    "Cashier",
    "MIS Executive",
    "Audit Executive",
    "GST Executive",
    "Payroll Executive",
    "Financial Analyst",
    "Collection Executive",
  ],
  "Banking / Insurance": [
    "Banking Executive",
    "Relationship Manager",
    "Loan Executive",
    "Credit Officer",
    "Insurance Advisor",
    "Insurance Sales Executive",
    "Bancassurance Executive",
    "Field Officer",
    "Collection Officer",
  ],
  "HR / Recruitment": [
    "HR Manager",
    "HR Executive",
    "HR Assistant",
    "HR Recruiter",
    "Recruitment Executive",
    "Talent Acquisition Executive",
    "Recruitment Coordinator",
    "Payroll Executive",
    "Training & Development Executive",
  ],
  "Office / Back Office": [
    "Office Administrator",
    "Office Coordinator",
    "Office Assistant",
    "Executive Assistant",
    "Personal Assistant",
    "Office Boy",
    "Back Office Executive",
    "Documentation Executive",
    "Computer Operator",
    "Clerk",
    "Typist",
  ],
  "Computer / IT": [
    "Data Entry Operator",
    "Computer Operator",
    "IT Support Executive",
    "Web Developer",
    "Software Developer",
    "App Developer",
    "Full Stack Developer",
    "Software Tester / QA",
    "Network Engineer",
    "System Administrator",
    "Cloud / DevOps Engineer",
    "Cyber Security Executive",
    "AI / ML Engineer",
  ],
  "BPO / Call Center": [
    "Telecaller",
    "Telesales Executive",
    "Call Center Executive",
    "Customer Care Executive",
    "Customer Support Executive",
    "Voice Process Executive",
    "Non-Voice Process Executive",
    "Chat Support Executive",
    "Customer Relationship Executive",
    "BPO Team Leader",
  ],
  "Sales / Marketing": [
    "Sales Executive",
    "Sales Manager",
    "Sales Officer",
    "Sales Coordinator",
    "Sales Consultant",
    "Marketing Executive",
    "Marketing Manager",
    "Field Sales Executive",
    "Business Development Executive",
    "Area Sales Manager",
    "Brand Promoter",
  ],
  "Digital Marketing / Creative": [
    "Digital Marketing Executive",
    "SEO Executive",
    "Social Media Executive",
    "Social Media Manager",
    "Content Writer",
    "Graphic Designer",
    "Video Editor",
    "Photographer",
    "Content Creator",
    "Performance Marketing Executive",
  ],
  "Retail / Store": [
    "Store Manager",
    "Store Incharge",
    "Store Executive",
    "Retail Sales Executive",
    "Cashier",
    "Counter Sales Executive",
    "Supermarket Staff",
    "Retail Associate",
    "Inventory Executive",
    "Visual Merchandiser",
  ],
  "Beauty / Salon / Spa": [
    "Beautician",
    "Beauty Therapist",
    "Makeup Artist",
    "Bridal Makeup Artist",
    "Hair Stylist",
    "Hairdresser",
    "Barber",
    "Nail Technician",
    "Facial Therapist",
    "Salon Receptionist",
    "Salon Manager",
    "Spa Therapist",
  ],
  "Cosmetic Shop": [
    "Cosmetic Store Manager",
    "Cosmetic Shop Assistant",
    "Cosmetic Sales Executive",
    "Beauty Advisor",
    "Counter Sales Executive",
    "Cosmetic Sales Associate",
    "Product Promoter",
  ],
  "Baby Care / Nanny": [
    "Baby Caretaker",
    "Babysitter",
    "Nanny",
    "Child Care Assistant",
    "Child Care Worker",
    "Infant Caregiver",
    "Kids Caretaker",
    "Day Care Assistant",
    "Day Care Teacher",
    "Live-in Nanny",
  ],
  "House Maid / Domestic Help": [
    "House Maid",
    "Home Helper",
    "Domestic Worker",
    "Household Cook",
    "Home Cook",
    "House Cleaner",
    "Domestic Helper",
    "Live-in Maid",
    "Part-time Maid",
    "Full-time Maid",
  ],
  "Elder Care / Caregiver": [
    "Elder Caretaker",
    "Patient Caretaker",
    "Home Caregiver",
    "Senior Care Assistant",
    "Patient Attendant",
    "Home Nurse",
    "Care Assistant",
    "Companion Caregiver",
  ],
  "Fire & Safety": [
    "Fire Safety Officer",
    "Fire Safety Supervisor",
    "Fireman",
    "Fire Technician",
    "Fire Alarm Technician",
    "Fire Fighting Technician",
    "Safety Officer",
    "Safety Supervisor",
    "Safety Executive",
    "EHS Executive",
    "EHS Officer",
    "Safety Engineer",
  ],
  "Facility Management": [
    "Facility Manager",
    "Facility Executive",
    "Facility Supervisor",
    "Facility Coordinator",
    "Maintenance Supervisor",
    "Maintenance Executive",
    "Site Facility Executive",
    "Facility Helper",
    "Utility Supervisor",
  ],
  "Automobile / Garage": [
    "Automobile Technician",
    "Automobile Mechanic",
    "Car Mechanic",
    "Bike Mechanic",
    "Service Advisor",
    "Service Technician",
    "Auto Electrician",
    "Denting Technician",
    "Painting Technician",
    "Workshop Supervisor",
    "Spare Parts Executive",
  ],
  "Power / Solar / Electrical": [
    "Electrical Engineer",
    "Electrical Technician",
    "Electrician",
    "Solar Technician",
    "Solar Engineer",
    "Solar Installer",
    "Solar Supervisor",
    "Solar Sales Executive",
    "Battery Technician",
    "Electrical Supervisor",
  ],
  "Mobile / Electronics": [
    "Mobile Technician",
    "Mobile Repair Technician",
    "Electronics Technician",
    "CCTV Technician",
    "CCTV Installer",
    "Computer Hardware Technician",
    "Laptop Technician",
    "Printer Technician",
    "Electronics Sales Executive",
  ],
  "Airport / Aviation": [
    "Airport Ground Staff",
    "Airport Customer Service",
    "Airport Security",
    "Baggage Handler",
    "Cargo Executive",
    "Airport Receptionist",
    "Ticketing Executive",
    "Reservation Executive",
    "Ground Operations Executive",
  ],
  "Agriculture / Farming": [
    "Farm Worker",
    "Agriculture Supervisor",
    "Agriculture Executive",
    "Agriculture Field Officer",
    "Farm Manager",
    "Nursery Worker",
    "Horticulture Worker",
    "Tractor Operator",
    "Agricultural Technician",
    "Field Assistant",
  ],
  "Dairy / Poultry / Animal Care": [
    "Dairy Worker",
    "Dairy Supervisor",
    "Dairy Farm Manager",
    "Milking Staff",
    "Cattle Caretaker",
    "Poultry Worker",
    "Poultry Farm Supervisor",
    "Poultry Farm Manager",
    "Animal Caretaker",
    "Veterinary Assistant",
  ],
  "Fitness / Gym": [
    "Gym Trainer",
    "Fitness Trainer",
    "Personal Trainer",
    "Yoga Instructor",
    "Zumba Instructor",
    "Gym Manager",
    "Gym Receptionist",
    "Fitness Consultant",
    "Sports Coach",
  ],
  "Media / Photography": [
    "Photographer",
    "Videographer",
    "Video Editor",
    "Photo Editor",
    "Camera Operator",
    "Content Creator",
    "News Reporter",
    "Digital Content Writer",
    "Production Assistant",
  ],
  "Legal / Documentation": [
    "Legal Assistant",
    "Legal Executive",
    "Legal Advisor",
    "Documentation Executive",
    "Compliance Executive",
    "Compliance Officer",
    "Court Clerk",
    "Legal Intern",
    "Contract Executive",
  ],
  "Internship / Apprenticeship": [
    "HR Intern",
    "Accounts Intern",
    "IT Intern",
    "Marketing Intern",
    "Graphic Design Intern",
    "Software Development Intern",
    "Mechanical Apprentice",
    "Electrical Apprentice",
    "Production Apprentice",
    "Quality Apprentice",
    "Graduate Apprentice",
    "Technician Apprentice",
  ],
  "Special Job Sections": [
    "Fresher Jobs",
    "Female Jobs",
    "Male Jobs",
    "Work From Home",
    "Part-Time Jobs",
    "Night Shift Jobs",
    "Day Shift Jobs",
    "Skilled Jobs",
    "Unskilled Jobs",
    "Urgent Hiring",
    "Featured Jobs",
    "Latest Jobs",
    "Local Jobs",
    "Other / \u0905\u0928\u094d\u092f Jobs",
  ],
};

export const jobCategoryNames: string[] = Object.keys(jobCategories);