export const jobCategories: Record<string, string[]> = {
  "Factory / Manufacturing": [
    "Production Executive",
    "Production Supervisor",
    "Production Manager",
    "Production Operator",
    "Assembly Operator",
    "Machine Operator",
    "Line Leader",
    "Line Supervisor",
    "Factory Worker",
    "Factory Helper",
  ],
  "ITI / Technical": [
    "ITI Fitter",
    "Electrician",
    "Welder",
    "Turner",
    "Machinist",
    "CNC Operator",
    "VMC Operator",
    "Technician",
    "Maintenance Technician",
    "Mechanical Technician",
    "Electrical Technician",
    "Electronics Technician",
  ],
  "Construction / Civil": [
    "Civil Engineer",
    "Site Engineer",
    "Civil Supervisor",
    "Site Supervisor",
    "Construction Worker",
    "Construction Helper",
    "Mason / Raj Mistri",
    "Bar Bender",
    "Shuttering Carpenter",
    "Carpenter",
    "Tile Fitter",
    "Plumber",
    "Painter",
  ],
  "Driver / Delivery": [
    "Car Driver",
    "Taxi / Cab Driver",
    "Bus Driver",
    "Truck / Heavy Vehicle Driver",
    "Ambulance Driver",
    "Delivery Executive",
    "Courier Executive",
    "Forklift Operator",
    "JCB Operator",
    "Crane Operator",
  ],
  "Warehouse / Logistics": [
    "Warehouse Executive",
    "Warehouse Supervisor",
    "Store Executive",
    "Store Keeper",
    "Inventory Executive",
    "Packing Staff",
    "Picker / Packer",
    "Dispatch Executive",
    "Logistics Executive",
    "Supply Chain Executive",
  ],
  "Security": [
    "Security Guard",
    "Security Supervisor",
    "Security Officer",
    "Security Manager",
    "CCTV Operator",
    "CCTV Supervisor",
    "Gatekeeper",
    "Security Executive",
    "Bouncer",
  ],
  "Housekeeping / Cleaning": [
    "Housekeeping Staff",
    "Housekeeping Supervisor",
    "Housekeeping Executive",
    "Room Attendant",
    "Cleaner",
    "Office Cleaner",
    "Hospital Cleaner",
    "Hotel Cleaner",
    "Laundry Attendant",
    "Deep Cleaning Staff",
  ],
  "Gardener / Landscaping": [
    "Gardener",
    "Garden Supervisor",
    "Landscape Worker",
    "Landscaping Supervisor",
    "Horticulture Assistant",
    "Nursery Worker",
    "Plant Caretaker",
    "Lawn Maintenance Worker",
  ],
  "Hotel / Hospitality": [
    "Hotel Manager",
    "Front Office Manager",
    "Receptionist",
    "Guest Relations Executive",
    "Reservation Executive",
    "Bell Boy",
    "Concierge",
    "Restaurant Manager",
    "Waiter / Steward",
    "Banquet Supervisor",
  ],
  "Restaurant / Food": [
    "Chef",
    "Sous Chef",
    "Commis Chef",
    "Cook",
    "Tandoor Chef",
    "Bakery Chef",
    "Kitchen Helper",
    "Dishwasher",
    "Food & Beverage Executive",
    "F&B Supervisor",
  ],
  "Hospital / Healthcare": [
    "Staff Nurse",
    "GNM / ANM Nurse",
    "Nursing Assistant",
    "ICU / OT Nurse",
    "Nursing Supervisor",
    "Hospital Administrator",
    "Patient Care Executive",
    "Ward Boy",
    "Lab Technician",
    "Phlebotomist",
    "X-Ray Technician",
    "ECG Technician",
    "Pharmacist",
    "Caregiver",
    "Patient Attendant",
  ],
  "Pharma / Medical": [
    "Medical Representative",
    "Medical Sales Executive",
    "Medical Store Manager",
    "Pharma Sales Executive",
    "Medical Coder",
    "Clinical Research Associate",
    "Drug Safety Associate",
  ],
  "Teaching / Education": [
    "School Principal",
    "School Coordinator",
    "PGT Teacher",
    "TGT Teacher",
    "PRT / Primary Teacher",
    "Nursery Teacher",
    "English Teacher",
    "Mathematics Teacher",
    "Science Teacher",
    "Computer Teacher",
    "Home Tutor",
    "Librarian",
  ],
  "Accounts & Finance": [
    "Accountant",
    "Accounts Executive",
    "Accounts Assistant",
    "Finance Executive",
    "Billing Executive",
    "Cashier",
    "MIS Executive",
    "Audit Executive",
    "GST Executive",
    "Payroll Executive",
    "Financial Analyst",
    "Collection Executive",
  ],
  "Banking / Insurance": [
    "Banking Executive",
    "Relationship Manager",
    "Loan Executive",
    "Credit Officer",
    "Insurance Advisor",
    "Insurance Sales Executive",
    "Bancassurance Executive",
    "Field Officer",
    "Collection Officer",
  ],
  "HR / Recruitment": [
    "HR Manager",
    "HR Executive",
    "HR Assistant",
    "HR Recruiter",
    "Recruitment Executive",
    "Talent Acquisition Executive",
    "Recruitment Coordinator",
    "Payroll Executive",
    "Training & Development Executive",
  ],
  "Office / Back Office": [
    "Office Administrator",
    "Office Coordinator",
    "Office Assistant",
    "Executive Assistant",
    "Personal Assistant",
    "Office Boy",
    "Back Office Executive",
    "Documentation Executive",
    "Computer Operator",
    "Clerk",
    "Typist",
  ],
  "Computer / IT": [
    "Data Entry Operator",
    "Computer Operator",
    "IT Support Executive",
    "Web Developer",
    "Software Developer",
    "App Developer",
    "Full Stack Developer",
    "Software Tester / QA",
    "Network Engineer",
    "System Administrator",
    "Cloud / DevOps Engineer",
    "Cyber Security Executive",
    "AI / ML Engineer",
  ],
  "BPO / Call Center": [
    "Telecaller",
    "Telesales Executive",
    "Call Center Executive",
    "Customer Care Executive",
    "Customer Support Executive",
    "Voice Process Executive",
    "Non-Voice Process Executive",
    "Chat Support Executive",
    "Customer Relationship Executive",
    "BPO Team Leader",
  ],
  "Sales / Marketing": [
    "Sales Executive",
    "Sales Manager",
    "Sales Officer",
    "Sales Coordinator",
    "Sales Consultant",
    "Marketing Executive",
    "Marketing Manager",
    "Field Sales Executive",
    "Business Development Executive",
    "Area Sales Manager",
    "Brand Promoter",
  ],
  "Digital Marketing / Creative": [
    "Digital Marketing Executive",
    "SEO Executive",
    "Social Media Executive",
    "Social Media Manager",
    "Content Writer",
    "Graphic Designer",
    "Video Editor",
    "Photographer",
    "Content Creator",
    "Performance Marketing Executive",
  ],
  "Retail / Store": [
    "Store Manager",
    "Store Incharge",
    "Store Executive",
    "Retail Sales Executive",
    "Cashier",
    "Counter Sales Executive",
    "Supermarket Staff",
    "Retail Associate",
    "Inventory Executive",
    "Visual Merchandiser",
  ],
  "Beauty / Salon / Spa": [
    "Beautician",
    "Beauty Therapist",
    "Makeup Artist",
    "Bridal Makeup Artist",
    "Hair Stylist",
    "Hairdresser",
    "Barber",
    "Nail Technician",
    "Facial Therapist",
    "Salon Receptionist",
    "Salon Manager",
    "Spa Therapist",
  ],
  "Cosmetic Shop": [
    "Cosmetic Store Manager",
    "Cosmetic Shop Assistant",
    "Cosmetic Sales Executive",
    "Beauty Advisor",
    "Counter Sales Executive",
    "Cosmetic Sales Associate",
    "Product Promoter",
  ],
  "Baby Care / Nanny": [
    "Baby Caretaker",
    "Babysitter",
    "Nanny",
    "Child Care Assistant",
    "Child Care Worker",
    "Infant Caregiver",
    "Kids Caretaker",
    "Day Care Assistant",
    "Day Care Teacher",
    "Live-in Nanny",
  ],
  "House Maid / Domestic Help": [
    "House Maid",
    "Home Helper",
    "Domestic Worker",
    "Household Cook",
    "Home Cook",
    "House Cleaner",
    "Domestic Helper",
    "Live-in Maid",
    "Part-time Maid",
    "Full-time Maid",
  ],
  "Elder Care / Caregiver": [
    "Elder Caretaker",
    "Patient Caretaker",
    "Home Caregiver",
    "Senior Care Assistant",
    "Patient Attendant",
    "Home Nurse",
    "Care Assistant",
    "Companion Caregiver",
  ],
  "Fire & Safety": [
    "Fire Safety Officer",
    "Fire Safety Supervisor",
    "Fireman",
    "Fire Technician",
    "Fire Alarm Technician",
    "Fire Fighting Technician",
    "Safety Officer",
    "Safety Supervisor",
    "Safety Executive",
    "EHS Executive",
    "EHS Officer",
    "Safety Engineer",
  ],
  "Facility Management": [
    "Facility Manager",
    "Facility Executive",
    "Facility Supervisor",
    "Facility Coordinator",
    "Maintenance Supervisor",
    "Maintenance Executive",
    "Site Facility Executive",
    "Facility Helper",
    "Utility Supervisor",
  ],
  "Automobile / Garage": [
    "Automobile Technician",
    "Automobile Mechanic",
    "Car Mechanic",
    "Bike Mechanic",
    "Service Advisor",
    "Service Technician",
    "Auto Electrician",
    "Denting Technician",
    "Painting Technician",
    "Workshop Supervisor",
    "Spare Parts Executive",
  ],
  "Power / Solar / Electrical": [
    "Electrical Engineer",
    "Electrical Technician",
    "Electrician",
    "Solar Technician",
    "Solar Engineer",
    "Solar Installer",
    "Solar Supervisor",
    "Solar Sales Executive",
    "Battery Technician",
    "Electrical Supervisor",
  ],
  "Mobile / Electronics": [
    "Mobile Technician",
    "Mobile Repair Technician",
    "Electronics Technician",
    "CCTV Technician",
    "CCTV Installer",
    "Computer Hardware Technician",
    "Laptop Technician",
    "Printer Technician",
    "Electronics Sales Executive",
  ],
  "Airport / Aviation": [
    "Airport Ground Staff",
    "Airport Customer Service",
    "Airport Security",
    "Baggage Handler",
    "Cargo Executive",
    "Airport Receptionist",
    "Ticketing Executive",
    "Reservation Executive",
    "Ground Operations Executive",
  ],
  "Agriculture / Farming": [
    "Farm Worker",
    "Agriculture Supervisor",
    "Agriculture Executive",
    "Agriculture Field Officer",
    "Farm Manager",
    "Nursery Worker",
    "Horticulture Worker",
    "Tractor Operator",
    "Agricultural Technician",
    "Field Assistant",
  ],
  "Dairy / Poultry / Animal Care": [
    "Dairy Worker",
    "Dairy Supervisor",
    "Dairy Farm Manager",
    "Milking Staff",
    "Cattle Caretaker",
    "Poultry Worker",
    "Poultry Farm Supervisor",
    "Poultry Farm Manager",
    "Animal Caretaker",
    "Veterinary Assistant",
  ],
  "Fitness / Gym": [
    "Gym Trainer",
    "Fitness Trainer",
    "Personal Trainer",
    "Yoga Instructor",
    "Zumba Instructor",
    "Gym Manager",
    "Gym Receptionist",
    "Fitness Consultant",
    "Sports Coach",
  ],
  "Media / Photography": [
    "Photographer",
    "Videographer",
    "Video Editor",
    "Photo Editor",
    "Camera Operator",
    "Content Creator",
    "News Reporter",
    "Digital Content Writer",
    "Production Assistant",
  ],
  "Legal / Documentation": [
    "Legal Assistant",
    "Legal Executive",
    "Legal Advisor",
    "Documentation Executive",
    "Compliance Executive",
    "Compliance Officer",
    "Court Clerk",
    "Legal Intern",
    "Contract Executive",
  ],
  "Internship / Apprenticeship": [
    "HR Intern",
    "Accounts Intern",
    "IT Intern",
    "Marketing Intern",
    "Graphic Design Intern",
    "Software Development Intern",
    "Mechanical Apprentice",
    "Electrical Apprentice",
    "Production Apprentice",
    "Quality Apprentice",
    "Graduate Apprentice",
    "Technician Apprentice",
  ],

  "Quality Control / QA": [
    "Quality Inspector", "Quality Checker", "Quality Control Executive", "Quality Control Engineer",
    "Quality Control Technician", "Quality Analyst", "Quality Assurance Executive", "Quality Assurance Engineer",
    "QA Technician", "QA Supervisor", "QA Manager", "Quality Manager", "Incoming Quality Inspector",
    "In-Process Quality Inspector", "Final Quality Inspector", "Production Quality Inspector",
    "Vendor Quality Engineer", "Supplier Quality Engineer", "Customer Quality Engineer", "Quality Auditor",
    "Internal Quality Auditor", "Process Auditor", "ISO Coordinator", "ISO Auditor",
    "Quality Documentation Executive", "Quality Control Chemist", "Quality Control Lab Technician",
    "NDT Technician", "NDT Inspector", "Metrology Technician", "Calibration Technician", "Quality Apprentice",
  ],

  "Purchase / Procurement": [
    "Purchase Executive", "Purchase Assistant", "Purchase Officer", "Purchase Manager",
    "Procurement Executive", "Procurement Officer", "Procurement Manager", "Procurement Specialist",
    "Procurement Coordinator", "Buyer", "Senior Buyer", "Strategic Buyer", "Purchase Coordinator",
    "Vendor Development Executive", "Vendor Development Manager", "Vendor Management Executive",
    "Supplier Relationship Executive", "Sourcing Executive", "Sourcing Manager",
    "Strategic Sourcing Specialist", "Purchase Analyst", "Procurement Analyst",
  ],

  "Production Planning / Industrial Engineering": [
    "Production Planner", "Production Planning Executive", "Production Planning Officer",
    "Production Planning Manager", "PPC Executive", "PPC Engineer", "PPC Officer", "PPC Manager",
    "Industrial Engineer", "Industrial Engineering Executive", "Process Engineer",
    "Process Improvement Engineer", "Process Improvement Executive", "Manufacturing Engineer",
    "Manufacturing Engineering Executive", "Operations Engineer", "Operations Executive",
    "Operations Manager", "Plant Engineer", "Plant Manager", "Work Study Officer",
    "Work Study Engineer", "Lean Manufacturing Engineer", "Continuous Improvement Engineer",
  ],

  "Maintenance / Engineering": [
    "Maintenance Engineer", "Maintenance Executive", "Maintenance Supervisor", "Maintenance Manager",
    "Mechanical Engineer", "Electrical Engineer", "Electronics Engineer", "Instrumentation Engineer",
    "Instrumentation Technician", "Mechatronics Engineer", "Mechatronics Technician", "Automation Engineer",
    "Automation Technician", "PLC Programmer", "PLC Technician", "Control Systems Engineer",
    "Utility Engineer", "Utility Technician", "Plant Maintenance Engineer", "Preventive Maintenance Engineer",
    "Maintenance Planner", "Maintenance Fitter", "Mechanical Supervisor", "Electrical Supervisor",
  ],

  "Research & Development": [
    "R&D Engineer", "R&D Executive", "R&D Manager", "Research Assistant", "Research Associate",
    "Research Scientist", "Development Engineer", "Product Development Engineer",
    "Product Development Executive", "Process Development Engineer", "Prototype Engineer",
    "R&D Technician", "Laboratory Research Assistant", "Technical Research Assistant",
    "Innovation Executive", "Innovation Manager",
  ],

  "Engineering Design": [
    "Design Engineer", "Mechanical Design Engineer", "Electrical Design Engineer",
    "Civil Design Engineer", "Structural Design Engineer", "CAD Engineer", "CAD Designer",
    "AutoCAD Designer", "SolidWorks Designer", "3D CAD Designer", "Design Executive", "Design Manager",
    "Draftsman", "Mechanical Draftsman", "Civil Draftsman", "Electrical Draftsman", "Design Technician",
  ],

  "Food Processing": [
    "Food Processing Operator", "Food Processing Executive", "Food Production Supervisor",
    "Food Production Manager", "Food Processing Technician", "Food Processing Worker", "Food Packer",
    "Food Packing Operator", "Food Product Handler", "Food Quality Inspector", "Food Quality Analyst",
    "Food Safety Executive", "Food Safety Officer", "Food Technologist", "Food Technology Executive",
    "Bakery Production Supervisor", "Baking Assistant", "Dairy Processing Operator",
    "Fruit Processing Operator", "Vegetable Processing Operator", "Cold Storage Operator",
  ],

  "Textile / Garment": [
    "Tailor", "Master Tailor", "Garment Worker", "Garment Operator", "Sewing Machine Operator",
    "Cutting Operator", "Fabric Cutter", "Embroidery Operator", "Textile Worker", "Textile Supervisor",
    "Textile Manager", "Garment Supervisor", "Garment Production Manager", "Textile Designer",
    "Fashion Designer", "Pattern Maker", "Pattern Master", "Quality Checker - Garments",
    "Garment Quality Inspector", "Finishing Operator", "Pressing Operator", "Textile Merchandiser",
  ],

  "Real Estate / Property": [
    "Real Estate Agent", "Property Dealer", "Real Estate Executive", "Real Estate Sales Executive",
    "Real Estate Sales Manager", "Property Consultant", "Property Advisor", "Leasing Executive",
    "Leasing Manager", "Property Manager", "Real Estate Relationship Manager",
    "Site Acquisition Executive", "Real Estate Telecaller", "Real Estate Business Development Executive",
    "Property Coordinator",
  ],

  "Travel / Tourism": [
    "Travel Agent", "Travel Consultant", "Travel Executive", "Tour Executive", "Tour Manager",
    "Tour Guide", "Travel Coordinator", "Travel Desk Executive", "Ticketing Executive",
    "Reservation Executive", "Visa Consultant", "Visa Processing Executive", "Holiday Consultant",
    "Travel Sales Executive", "Tourism Executive", "Destination Manager", "Airport Travel Executive",
  ],

  "Event Management": [
    "Event Executive", "Event Coordinator", "Event Manager", "Event Planner", "Event Producer",
    "Event Sales Executive", "Wedding Planner", "Wedding Coordinator", "Wedding Manager",
    "Event Operations Executive", "Event Marketing Executive", "Exhibition Coordinator",
    "Conference Coordinator", "Stage Manager", "Event Assistant",
  ],

  "Customer Service / Client Success": [
    "Customer Service Executive", "Customer Service Representative", "Customer Service Officer",
    "Customer Service Manager", "Customer Support Executive", "Customer Support Representative",
    "Client Service Executive", "Client Relationship Executive", "Client Relationship Manager",
    "Client Success Executive", "Customer Success Executive", "Customer Success Manager",
    "Customer Experience Executive", "Customer Experience Manager", "Helpdesk Executive",
    "Service Desk Executive", "Technical Support Executive", "Complaint Resolution Executive",
  ],

  "Telecom": [
    "Telecom Technician", "Telecom Engineer", "Telecom Field Engineer", "Network Technician",
    "Network Engineer", "Fiber Technician", "Fiber Optic Technician", "Fiber Splicing Technician",
    "Broadband Technician", "Installation Technician", "Telecom Field Executive", "Telecom Supervisor",
    "Telecom Project Engineer", "Tower Technician", "Tower Climber", "RF Engineer", "NOC Engineer",
    "NOC Executive",
  ],

  "Chemical / Petroleum": [
    "Chemical Engineer", "Chemical Technician", "Chemical Operator", "Process Operator", "Plant Operator",
    "Chemical Plant Operator", "Chemical Supervisor", "Chemical Plant Manager", "Process Engineer",
    "Petroleum Engineer", "Oil & Gas Technician", "Refinery Operator", "Refinery Technician",
    "Production Chemist", "Quality Control Chemist", "Laboratory Chemist", "Chemical Lab Technician",
  ],

  "Mining / Metals": [
    "Mining Engineer", "Mining Supervisor", "Mining Technician", "Mine Operator", "Mining Surveyor",
    "Mine Foreman", "Blasting Assistant", "Geologist", "Geological Assistant", "Metallurgical Engineer",
    "Metallurgy Technician", "Foundry Worker", "Foundry Supervisor", "Furnace Operator",
    "Steel Plant Operator", "Metal Fabricator",
  ],

  "Architecture / Interior Design": [
    "Architect", "Junior Architect", "Senior Architect", "Architectural Assistant", "Interior Designer",
    "Interior Design Assistant", "Interior Design Executive", "Interior Design Consultant",
    "Interior Designer - Residential", "Interior Designer - Commercial", "3D Visualizer",
    "3D Interior Designer", "Architectural Draughtsman", "CAD Designer", "Site Interior Supervisor",
    "Furniture Designer",
  ],

  "Environment / Waste Management": [
    "Environmental Engineer", "Environmental Executive", "Environmental Officer", "Environmental Consultant",
    "EHS Engineer", "Waste Management Executive", "Waste Management Supervisor", "Waste Collection Worker",
    "Waste Segregation Worker", "Recycling Worker", "Recycling Supervisor", "Water Treatment Operator",
    "STP Operator", "ETP Operator", "Water Quality Technician", "Pollution Control Officer",
  ],

  "Investment / Wealth Management": [
    "Investment Analyst", "Equity Research Analyst", "Research Analyst", "Financial Advisor",
    "Investment Advisor", "Wealth Manager", "Wealth Management Executive", "Portfolio Manager",
    "Mutual Fund Advisor", "Mutual Fund Executive", "Stock Broker", "Dealer", "Equity Dealer",
    "Capital Market Executive", "Investment Banking Analyst", "Investment Banking Associate",
    "Risk Analyst", "Risk Manager", "Treasury Executive", "Treasury Manager",
  ],

  "Insurance": [
    "Insurance Advisor", "Insurance Agent", "Insurance Sales Executive", "Insurance Relationship Manager",
    "Insurance Manager", "Insurance Officer", "Insurance Operations Executive", "Insurance Claims Executive",
    "Claims Officer", "Claims Manager", "Claims Analyst", "Underwriting Executive", "Underwriter",
    "Underwriting Manager", "Insurance Processing Executive", "Policy Servicing Executive",
    "Insurance Telecaller", "Bancassurance Executive", "Insurance Renewal Executive",
  ],

  "Export / Import / International Trade": [
    "Export Executive", "Export Manager", "Import Executive", "Import Manager",
    "Export Documentation Executive", "Import Documentation Executive", "EXIM Executive", "EXIM Manager",
    "International Trade Executive", "Shipping Executive", "Shipping Coordinator",
    "Freight Forwarding Executive", "Customs Documentation Executive", "Customs Clearance Executive",
    "Logistics Coordinator", "International Sales Executive",
  ],

  "Government / Public Sector": [
    "Government Clerk", "Junior Assistant", "Senior Assistant", "Data Entry Operator", "Office Assistant",
    "LDC", "UDC", "Stenographer", "Junior Secretariat Assistant", "Government Accountant",
    "Tax Assistant", "Income Tax Inspector", "GST Inspector", "Police Constable", "Sub Inspector",
    "Forest Guard", "Forest Officer", "Patwari", "Village Development Officer", "Panchayat Assistant",
    "Government Teacher", "Government Engineer", "Junior Engineer", "Assistant Engineer",
    "Government Nurse", "Government Pharmacist", "Lab Technician",
  ],

  "Laboratory / Scientific": [
    "Lab Assistant", "Laboratory Technician", "Lab Technician", "Laboratory Analyst",
    "Laboratory Executive", "Research Assistant", "Research Associate", "Chemist", "Microbiologist",
    "Biotechnologist", "Pathology Technician", "Sample Collection Technician", "Lab Supervisor",
    "Lab Manager", "Scientific Assistant", "Scientific Officer",
  ],

  "Printing / Packaging": [
    "Printing Operator", "Printing Machine Operator", "Offset Printing Operator",
    "Digital Printing Operator", "Printing Supervisor", "Printing Manager", "Packaging Operator",
    "Packaging Supervisor", "Packaging Executive", "Packaging Manager", "Packing Machine Operator",
    "Packaging Designer", "Prepress Operator", "DTP Operator", "Binding Operator",
    "Printing Quality Inspector", "Packaging Quality Inspector",
  ],

  "Fashion / Apparel": [
    "Fashion Designer", "Fashion Design Assistant", "Fashion Stylist", "Fashion Consultant",
    "Fashion Merchandiser", "Apparel Merchandiser", "Garment Merchandiser", "Fashion Illustrator",
    "Pattern Designer", "Pattern Master", "Tailor", "Master Tailor", "Boutique Manager",
    "Boutique Assistant", "Fashion Sales Executive",
  ],

  "Renewable Energy": [
    "Solar Technician", "Solar Engineer", "Solar Installer", "Solar Supervisor", "Solar Sales Executive",
    "Solar Project Engineer", "Solar Project Manager", "Solar O&M Technician",
    "Solar Maintenance Technician", "Wind Turbine Technician", "Wind Energy Engineer",
    "Wind Farm Technician", "Renewable Energy Engineer", "Renewable Energy Technician",
    "Renewable Energy Project Manager", "Battery Technician", "Battery Engineer",
    "Energy Storage Technician", "EV Charging Technician",
  ],

  "EV / Electric Vehicle": [
    "EV Technician", "EV Mechanic", "EV Service Technician", "EV Maintenance Technician",
    "EV Battery Technician", "EV Battery Engineer", "EV Charging Technician",
    "EV Charging Station Operator", "EV Service Advisor", "EV Sales Executive", "EV Sales Consultant",
    "EV Diagnostic Technician", "Automotive Electrician", "Electric Vehicle Engineer",
    "EV Production Operator",
  ],

  "Semiconductor / Electronics Manufacturing": [
    "Semiconductor Technician", "Semiconductor Engineer", "Electronics Manufacturing Technician",
    "Electronics Production Operator", "PCB Assembly Operator", "PCB Technician", "SMT Operator",
    "SMT Technician", "Electronics Quality Inspector", "Electronics Testing Technician",
    "Test Engineer", "Process Engineer", "VLSI Engineer", "Embedded Engineer",
    "Embedded Systems Engineer", "Chip Design Engineer", "IC Design Engineer",
    "Semiconductor Process Engineer", "Semiconductor Equipment Technician",
  ],

  "Special Job Sections": [
    "Fresher Jobs",
    "Female Jobs",
    "Male Jobs",
    "Work From Home",
    "Part-Time Jobs",
    "Night Shift Jobs",
    "Day Shift Jobs",
    "Skilled Jobs",
    "Unskilled Jobs",
    "Urgent Hiring",
    "Featured Jobs",
    "Latest Jobs",
    "Local Jobs",
    "Other / \u0905\u0928\u094d\u092f Jobs",
  ],
};

export const jobCategoryNames: string[] = Object.keys(jobCategories);
