export const jobFields = [

  // IT & Technology

  "IT / Software",
  "Computer Operator",
  "Data Entry",
  "Web Development",
  "Software Development",
  "Frontend Development",
  "Backend Development",
  "Full Stack Development",
  "Mobile App Development",
  "Software Testing / QA",
  "Cloud / DevOps",
  "Cyber Security",
  "Data Analytics",
  "Data Science / AI / ML",
  "Technical Support",
  "UI / UX Design",
  "Product Management",
  "Telecom",
  "Electronics / Hardware",
  "Semiconductor / Electronics Manufacturing",

  // Digital Marketing & Creative

  "Digital Marketing",
  "SEO",
  "SEM / Google Ads",
  "Social Media",
  "Social Media Manager",
  "Content Writing",
  "Copywriting",
  "Video Editing",
  "Photography",
  "Videography",
  "Content Creator",
  "Influencer Marketing",
  "Performance Marketing",

  // Banking & Finance

  "Banking",
  "Insurance",
  "Accounts & Finance",
  "Finance & Collection",
  "Investment / Wealth Management",
  "Stock Market / Capital Market",
  "Equity Research",
  "Financial Advisory",
  "Credit / Loan",
  "Risk Management",
  "Taxation / GST",
  "Audit",
  "Payroll",
  "Treasury",

  // HR & Office

  "HR / Recruitment",
  "Talent Acquisition",
  "Training & Development",
  "Payroll / HR Operations",
  "Office / Back Office",
  "Receptionist / Front Desk",
  "Administrative / Administration",
  "Executive Assistant / Personal Assistant",
  "Documentation",
  "Computer Operator",
  "Clerk / Typist",
  "Telecaller / Customer Care",
  "BPO / Call Center",
  "Customer Service",
  "Customer Support",
  "Client Relationship",
  "Client Success",
  "Supervisor / Team Leader",

  // Sales & Business

  "Sales",
  "Marketing",
  "Business Development",
  "Field Sales",
  "Retail / Store",
  "Real Estate",
  "Property Management",
  "Business Operations",
  "Procurement / Purchase",
  "Vendor Management",
  "Export / Import",
  "International Trade",

  // Healthcare & Medical

  "Hospital / Healthcare",
  "Nursing / Medical",
  "Pharma",
  "Medical Sales",
  "Medical Coding",
  "Clinical Research",
  "Laboratory / Scientific",
  "Quality / Laboratory",
  "Pathology",
  "Diagnostic Services",
  "Pharmacy",
  "Patient Care",
  "Home Healthcare",
  "Elder Care / Caregiver",
  "Veterinary / Animal Healthcare",

  // Education

  "Teaching / Education",
  "School Teacher",
  "College / University",
  "Coaching / Training",
  "Home Tutor",
  "Special Education",
  "Education Administration",
  "Library / Librarian",

  // Engineering & Technical

  "Civil Engineering",
  "Mechanical Engineering",
  "Electrical Engineering",
  "Electronics Engineering",
  "Chemical Engineering",
  "Industrial Engineering",
  "Production Engineering",
  "Design / CAD",
  "Architecture",
  "Interior Design",
  "Instrumentation",
  "Automation / PLC",
  "Mechatronics",
  "Environmental Engineering",
  "Mining / Metallurgy",
  "Electrician",
  "Fitter",
  "Welder",
  "Turner / Machinist",
  "CNC / VMC Operator",
  "Technician / Maintenance",
  "ITI Jobs",
  "Technical Apprentice",

  // Manufacturing & Production

  "Factory Worker",
  "Helper / Worker",
  "Manufacturing",
  "Production",
  "Production Planning / PPC",
  "Assembly",
  "Machine Operator",
  "Industrial Operations",
  "Plant Operations",
  "Maintenance / Engineering",
  "Quality Control / QA",
  "Quality Inspector",
  "Quality Checker",
  "Quality Assurance",
  "Quality Auditor",
  "Supplier / Vendor Quality",
  "Research & Development",
  "Product Development",
  "Process Development",
  "Food Processing",
  "Chemical / Petroleum",
  "Textile / Garment",
  "Fashion / Apparel",
  "Printing / Packaging",
  "Paper / Packaging",
  "Steel / Metal",
  "Foundry",
  "Plastic / Polymer",
  "Pharmaceutical Manufacturing",

  // Warehouse, Supply Chain & Logistics

  "Warehouse / Packing",
  "Warehouse Management",
  "Inventory",
  "Store / Storekeeping",
  "Picker / Packer",
  "Dispatch",
  "Logistics & Transport",
  "Supply Chain",
  "Procurement / Purchase",
  "Purchase",
  "Freight / Cargo",
  "Shipping",
  "Courier",
  "Export / Import",

  // Construction & Infrastructure

  "Construction",
  "Civil Works",
  "Site Engineering",
  "Site Supervision",
  "Mason / Raj Mistri",
  "Carpenter",
  "Shuttering",
  "Bar Bending",
  "Plumbing",
  "Painting",
  "Tile Fitting",
  "Road / Infrastructure",
  "Architecture / Planning",
  "Surveying",

  // Driver & Transport

  "Driver",
  "Car Driver",
  "Taxi / Cab Driver",
  "Bus Driver",
  "Truck / Heavy Vehicle Driver",
  "Ambulance Driver",
  "Delivery Executive",
  "Courier Executive",
  "Forklift Operator",
  "JCB Operator",
  "Crane Operator",
  "Transport Operations",

  // Automobile & EV

  "Automobile / Garage",
  "Automobile Technician",
  "Automobile Mechanic",
  "Car Mechanic",
  "Bike Mechanic",
  "Service Advisor",
  "Vehicle Service",
  "Auto Electrician",
  "Denting / Painting",
  "Spare Parts",
  "EV / Electric Vehicle",
  "EV Technician",
  "EV Mechanic",
  "EV Battery",
  "EV Charging",
  "EV Service",
  "EV Sales",

  // Power / Energy

  "Power / Electrical",
  "Electrical Installation",
  "Electrical Maintenance",
  "Solar Energy",
  "Solar Technician",
  "Solar Engineer",
  "Solar Installation",
  "Solar O&M",
  "Renewable Energy",
  "Wind Energy",
  "Battery / Energy Storage",
  "EV Charging Infrastructure",

  // Hospitality

  "Hotel / Hospitality",
  "Hotel Management",
  "Front Office",
  "Reception / Guest Relations",
  "Housekeeping",
  "Room Attendant",
  "Restaurant / Food",
  "Chef / Cooking",
  "Kitchen Staff",
  "Food & Beverage",
  "Waiter / Steward",
  "Banquet",
  "Catering",
  "Bakery",
  "Food Processing",

  // Travel & Tourism

  "Travel / Tourism",
  "Travel Agent",
  "Travel Consultant",
  "Tour Management",
  "Tour Guide",
  "Ticketing",
  "Reservation",
  "Visa Processing",
  "Travel Desk",
  "Airport / Aviation",
  "Airport Ground Staff",
  "Airport Operations",
  "Cargo / Baggage Handling",

  // Sales, Retail & Customer Service

  "Retail / Store",
  "Supermarket",
  "Counter Sales",
  "Retail Sales",
  "Store Management",
  "Visual Merchandising",
  "Customer Service",
  "Customer Support",
  "Relationship Management",
  "Field Sales",
  "Business Development",
  "Brand Promotion",

  // Security & Safety

  "Security",
  "Security Guard",
  "Security Supervisor",
  "Security Officer",
  "CCTV Operator",
  "CCTV Technician",
  "Loss Prevention",
  "Fire & Safety",
  "Fire Safety Officer",
  "Fire Technician",
  "Safety Officer",
  "Safety Supervisor",
  "EHS / Environment Health & Safety",

  // Facility & Maintenance

  "Facility Management",
  "Facility Manager",
  "Facility Executive",
  "Facility Supervisor",
  "Building Maintenance",
  "Electrical Maintenance",
  "Mechanical Maintenance",
  "Utility Operations",
  "Housekeeping / Cleaning",
  "Deep Cleaning",
  "Laundry",
  "Gardening / Landscaping",

  // Agriculture & Farming

  "Agriculture",
  "Agriculture Field Work",
  "Agriculture Management",
  "Agriculture Officer",
  "Agriculture Technician",
  "Farming",
  "Farm Worker",
  "Farm Manager",
  "Horticulture",
  "Nursery",
  "Organic Farming",
  "Greenhouse Farming",
  "Mushroom Farming",
  "Beekeeping",
  "Fisheries / Aquaculture",
  "Dairy",
  "Poultry",
  "Animal Care",
  "Veterinary",

  // Beauty & Personal Care

  "Beauty & Salon",
  "Beautician",
  "Hair Stylist",
  "Barber",
  "Makeup Artist",
  "Bridal Makeup",
  "Nail Technician",
  "Beauty Therapist",
  "Spa",
  "Wellness",

  // Fashion & Garment

  "Tailoring / Garment",
  "Tailor",
  "Master Tailor",
  "Sewing Machine Operator",
  "Garment Worker",
  "Garment Production",
  "Garment Quality",
  "Embroidery",
  "Fashion Design",
  "Fashion Merchandising",
  "Boutique",

  // Media & Entertainment

  "Media / Photography",
  "Photography",
  "Videography",
  "Video Editing",
  "Photo Editing",
  "Camera Operator",
  "Content Creation",
  "News / Journalism",
  "Digital Media",
  "Production Assistant",
  "Event Management",
  "Event Planning",
  "Wedding Planning",

  // Legal & Compliance

  "Legal / Documentation",
  "Legal Assistant",
  "Legal Executive",
  "Legal Advisor",
  "Lawyer / Advocate",
  "Court / Legal Clerk",
  "Compliance",
  "Compliance Officer",
  "Contract Management",
  "Documentation",
  "Company Secretary",

  // Government & Public Sector

  "Government / Public Sector",
  "Government Clerk",
  "Government Assistant",
  "Government Accountant",
  "Government Teacher",
  "Government Nurse",
  "Government Engineer",
  "Junior Engineer",
  "Police",
  "Defence",
  "Forest Department",
  "Revenue / Patwari",
  "Municipal / Local Government",
  "Public Sector Jobs",

  // Environment & Waste Management

  "Environment / Waste Management",
  "Environmental Services",
  "Environmental Engineer",
  "Environmental Officer",
  "Waste Management",
  "Waste Collection",
  "Recycling",
  "Water Treatment",
  "STP / ETP Operator",
  "Pollution Control",

  // Fitness & Sports

  "Fitness / Gym",
  "Gym Trainer",
  "Personal Trainer",
  "Fitness Trainer",
  "Yoga Instructor",
  "Zumba Instructor",
  "Sports Coach",
  "Gym Receptionist",
  "Gym Manager",
  "Sports / Recreation",

  // Child & Elder Care

  "Baby Care / Nanny",
  "Nanny",
  "Babysitter",
  "Child Care",
  "Day Care",
  "Day Care Teacher",
  "Elder Care / Caregiver",
  "Home Caregiver",
  "Patient Attendant",
  "Home Nurse",
  "Senior Care Assistant",
  "Domestic Help / House Maid",
  "House Maid",
  "Domestic Worker",
  "Home Cook",
  "House Cleaner",

  // Other Professional Fields

  "Research",
  "Scientific Research",
  "Consulting",
  "Operations",
  "Project Management",
  "Business Analyst",
  "Management",
  "NGO / Social Work",
  "Event Management",
  "Freelance / Gig Work",

  // Employment Type / Special Job Categories

  "Work From Home",
  "Hybrid Jobs",
  "Part-Time Jobs",
  "Full-Time Jobs",
  "Contract Jobs",
  "Temporary Jobs",
  "Private Jobs",
  "Government Jobs",
  "Fresher Jobs",
  "Internship",
  "Apprenticeship",
  "Graduate Jobs",
  "Skilled Jobs",
  "Unskilled Jobs",
  "Urgent Hiring",
  "Night Shift Jobs",
  "Day Shift Jobs",
  "Female Jobs",
  "Male Jobs",
  "Local Jobs",
  "Other",

];